export declare const Bi: any;
export declare const CM: any;
export declare const EL: any;
export declare const LM: any;
export declare const MP: any;
export declare const R3: any;
export declare const RP: any;
export declare const Si: any;
export declare const SM: any;
export declare const T: any;
export declare const TM: any;
export declare const VL: any;
export declare const VR: any;
export declare function getClientInitials(code: string): any;
